/* ------------------------------------------------------------------------
 * The geometry of Foyer's logo — GENERATED by tools/gen_logo.py.
 * Do not edit: the drawing changes there, and the SVGs of docs/logo/ come
 * from the same place.
 *
 * Mark units: a square of LOGO_HEIGHT. The logo with the name is
 * LOGO_WIDTH wide. See logo.c for how it is drawn.
 * --------------------------------------------------------------------- */
#ifndef LOGO_SHAPE_H
#define LOGO_SHAPE_H

#include <stdbool.h>

#define LOGO_HEIGHT 64
#define LOGO_WIDTH  180

typedef enum { LOGO_LINE, LOGO_ARC, LOGO_CIRCLE, LOGO_RECT } logo_kind_t;

/* p[0..2]: the points of a line; for the others
     arc     p[0] centre, p[1].x radius, p[2] start and end in degrees
     circle  p[0] centre, p[1].x radius
     rect    p[0] top-left corner, p[1] width and height */
typedef struct {
    logo_kind_t kind;
    char        role;       /* 'i' ink, 'a' amber */
    float       opa;
    float       width;
    bool        rounded;
    int         points;
    struct { float x, y; } p[3];
} logo_prim_t;

static const logo_prim_t logo_mark[] = {
    { LOGO_LINE, 'i', 1.00f, 3.60f, true, 3, { {21.00f, 37.00f}, {32.00f, 28.00f}, {43.00f, 37.00f} } },
    { LOGO_LINE, 'i', 0.60f, 3.60f, true, 3, { {14.00f, 31.50f}, {32.00f, 17.00f}, {50.00f, 31.50f} } },
    { LOGO_LINE, 'i', 0.32f, 3.60f, true, 3, { {7.00f, 26.00f}, {32.00f, 6.00f}, {57.00f, 26.00f} } },
    { LOGO_RECT, 'a', 1.0f, 0, false, 0, { {26.00f, 47.00f}, {12.00f, 10.00f} } },
    { LOGO_CIRCLE, 'a', 1.0f, 0, false, 0, { {32.00f, 47.00f}, {6.00f, 0} } },
    { LOGO_LINE, 'i', 1.00f, 3.60f, true, 2, { {16.00f, 57.00f}, {48.00f, 57.00f} } },
};
#define LOGO_MARK_N (sizeof logo_mark / sizeof logo_mark[0])

static const logo_prim_t logo_name[] = {
    { LOGO_RECT, 'i', 1.0f, 0, false, 0, { {77.00f, 21.00f}, {3.40f, 22.00f} } },
    { LOGO_RECT, 'i', 1.0f, 0, false, 0, { {77.00f, 21.00f}, {11.00f, 3.40f} } },
    { LOGO_RECT, 'i', 1.0f, 0, false, 0, { {77.00f, 30.30f}, {9.00f, 3.40f} } },
    { LOGO_ARC, 'i', 1.0f, 3.40f, false, 0, { {105.50f, 32.00f}, {9.80f, 0}, {0.00f, 360.00f} } },
    { LOGO_LINE, 'i', 1.00f, 3.40f, false, 2, { {124.30f, 22.00f}, {131.50f, 32.60f} } },
    { LOGO_LINE, 'i', 1.00f, 3.40f, false, 2, { {138.70f, 22.00f}, {131.50f, 32.60f} } },
    { LOGO_RECT, 'i', 1.0f, 0, false, 0, { {129.80f, 32.00f}, {3.40f, 11.00f} } },
    { LOGO_RECT, 'i', 1.0f, 0, false, 0, { {146.50f, 21.00f}, {3.40f, 22.00f} } },
    { LOGO_RECT, 'i', 1.0f, 0, false, 0, { {146.50f, 21.00f}, {11.00f, 3.40f} } },
    { LOGO_RECT, 'i', 1.0f, 0, false, 0, { {146.50f, 30.30f}, {9.50f, 3.40f} } },
    { LOGO_RECT, 'i', 1.0f, 0, false, 0, { {146.50f, 39.60f}, {11.00f, 3.40f} } },
    { LOGO_RECT, 'i', 1.0f, 0, false, 0, { {164.50f, 21.00f}, {3.40f, 22.00f} } },
    { LOGO_RECT, 'i', 1.0f, 0, false, 0, { {164.50f, 21.00f}, {6.50f, 3.40f} } },
    { LOGO_RECT, 'i', 1.0f, 0, false, 0, { {164.50f, 30.30f}, {6.50f, 3.40f} } },
    { LOGO_ARC, 'i', 1.0f, 3.40f, false, 0, { {171.00f, 27.35f}, {4.65f, 0}, {270.00f, 90.00f} } },
    { LOGO_LINE, 'i', 1.00f, 3.40f, false, 2, { {170.50f, 32.00f}, {176.70f, 42.20f} } },
};
#define LOGO_NAME_N (sizeof logo_name / sizeof logo_name[0])

#endif /* LOGO_SHAPE_H */
